name: Terraform Apply
run-name: Terraform Apply - ${{ github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to (e.g., devl, test, prod)"
        required: true
        type: choice
        options:
          - devl
          - test
          - prod
        default: devl
      terraform-dir:
        description: "Terraform directory (e.g., infra/databricks/tf)"
        required: true
        type: string
        default: "infra/databricks/tf"
      tf-vars-file:
        description: "Terraform variables file name"
        required: true
        type: string
        default: "terraform.tfvars"


jobs:
  apply:
    name: 🚧 Run Terraform Apply  
    uses: subhamay-bhattacharyya-gha/tf-deploy-multi-reusable-wf/.github/workflows/terraform-deploy.yaml@feature/GHA-0011-add-tflint-in-the-workflo
    with:
      cloud-provider: databricks
      tflint-ver: ${{ vars.TF_LINT_VER }}
      backend-type: remote
      aws-region: ${{ vars.AWS_REGION }}
      tf-vars-file: terraform.tfvars
    secrets:
      tfc-token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      databricks-host: ${{ secrets.DATABRICKS_HOST }}
      databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
