name: Terraform Apply
run-name: Terraform Apply - ${{ github.ref_name }}

on:
  workflow_dispatch:
    # inputs:
    #   cloud-provider:
    #     description: "Target cloud provider"
    #     required: true
    #     type: choice
    #     options:
    #       - databricks


jobs:
  apply:
    name: 🚧 Run Terraform Apply  
    uses: subhamay-bhattacharyya-gha/tf-deploy-multi-reusable-wf/.github/workflows/terraform-deploy.yaml@main
    with:
      cloud-provider: databricks
      tflint-ver: ${{ vars.TF_LINT_VER }}
      backend-type: remote
      aws-region: ${{ vars.AWS_REGION }}
      tf-vars-file: terraform.tfvars
    secrets:
      tfc-token: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}
      databricks-host: ${{ secrets.DATABRICKS_HOST }}
      databricks-token: ${{ secrets.DATABRICKS_TOKEN }}
